# mysql 等创建好数据库以后，可用这个启动
# windows dockerdesktop 版本适用
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-conf:/etc/mysql
      - mysql-log:/var/log/mysql
    networks:
      snipeit-net:
        ipv4_address: 172.21.1.2


  snipeit:
    image: snipe/snipe-it:latest
    container_name: snipe-it
    env_file:
      - my_env_file
    ports:
      - "5080:80"
    volumes:
      - snipeit-data:/var/lib/snipeit
      - snipeit-log:/var/www/html/storage/logs
    networks:
      snipeit-net:
        ipv4_address: 172.21.1.3
      
    depends_on:
      - mysql

networks:
  snipeit-net:
    driver: bridge
    ipam:
        config:
          - subnet: 172.21.0.0/16
            gateway: 172.21.0.1    

volumes:
  mysql-data:
  mysql-conf:
  mysql-log:
  snipeit-data:
  snipeit-log:
  # 可指定 windows 系统下目录
  # snipeit-tapes-brother:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: /E/Download/Other/WSL/tapes