services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    # command:
    #   - "--config.file=/etc/prometheus/prometheus.yml"
    #   - "--storage.tsdb.path=/prometheus"
    #   - "--web.console.libraries=/usr/share/prometheus/console_libraries"
    #   - "--web.console.templates=/usr/share/prometheus/consoles"
    # 开启打开 prometheus 页面时需要验证
    #   - "--web.config.file=/etc/prometheus/web.yml"
    ports:
      - "9090:9090"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/etc/prometheus
      - ./data:/prometheus
    # depends_on:
    #   - xxxxxx
    networks:
      mylan:
        ipv4_address: 172.21.1.6

networks:
  # 沿用之前创建的网络，方便管理。
  mylan:
    external: true